// Scene management for Bevy version

pub mod login_scene;
pub mod select_scene;
pub mod game_scene;

// Re-export login scene items
pub use login_scene::handle_button_hover;
pub use login_scene::{
    setup_login_scene,
    init_network_channel,
    cleanup_login_scene,
    update_background_animation,
    handle_text_input,
    update_input_display,
    handle_input_focus,
    handle_tab_focus,
    update_input_borders,
    update_cursor_blink,
    handle_button_press,
    handle_button_clicks,
    handle_dialog_buttons,
    handle_dialog_text_input,
    update_dialog_input_display,
    handle_dialog_tab_focus,
    handle_dialog_input_click,
    update_dialog_input_borders,
    update_dialog_cursor_visibility,
    handle_login_message,
    handle_close_message,
    handle_new_account_message,
    handle_password_change_message,
    handle_view_key_message,
    LoginButtonPressed,
    NewAccountButtonPressed,
    PasswordChangeButtonPressed,
    ViewKeyButtonPressed,
    CloseButtonPressed,
};

// Re-export select scene items (新架构)
pub use select_scene::{
    setup_select_scene,
    cleanup_select_scene,
    update_character_animation,
    update_character_slots,
    update_button_textures,
    handle_slot_clicks,
    update_slot_texts,
    update_slot_text_colors,
    handle_slot_hover,
    DialogState,
    handle_dialog_button_clicks,
    handle_dialog_button_hover,
    update_dialog_character_preview,
};
// 使用别名避免与 login_scene::handle_button_clicks 冲突
pub use select_scene::handle_button_clicks as handle_select_button_clicks;
// 使用别名避免与 login_scene::init_network_channel 冲突
pub use select_scene::init_network_channel as init_select_network_channel;

// Re-export game scene items
pub use game_scene::{
    setup_game_scene,
    cleanup_game_scene,
    update_game_time,
    handle_player_input,
    handle_player_movement,
    update_player_position,
    update_hud_display,
    handle_quickslot_hover,
    message_handle_player_move,
    message_handle_open_chat,
    message_handle_close_chat,
    message_handle_open_inventory,
    message_handle_close_inventory,
    message_handle_open_skills,
    message_handle_close_skills,
    message_handle_pause_game,
    message_handle_exit_game,
    message_handle_interact_npc,
    message_handle_use_skill,
    // Phase 1: 玩家实体管理系统
    update_player_stats_system,
    process_buffs_system,
    // Phase 2: 地图加载和渲染
    load_map_system,
    create_map_layers_system,
    spawn_map_objects_system,
    update_map_state_system,
    handle_map_collision_system,
    // Phase 4-5: 新渲染架构 (摄像机 + 地图加载)
    MapRenderData,
    MapLoadRequest,
    GameCamera,
    render_map_system,
    update_animation_system,
    camera_follow_system_new,
    camera_zoom_system,
    load_map_system_new,
    setup_game_rendering,
    cleanup_game_rendering,
    setup_map_renderer,  // ← 新增
    debug_transforms_system,  // ← 调试系统
    toggle_grid_system,  // ← 网格调试：按G键切换
    render_grid_system,  // ← 网格调试：绘制网格线
    // Phase 3: NPC 和对象交互
    setup_dialogue_system,
    detect_interaction_system,
    handle_interaction_system,
    update_dialogue_display_system,
    handle_dialogue_choice_system,
    message_handle_npc_dialogue,
    // Phase 4: 聊天系统
    setup_chat_system,
    process_chat_input_system,
    process_chat_commands_system,
    receive_chat_messages_system,
    filter_chat_messages_system,
    apply_word_filter_system,
    update_chat_display_system,
    manage_chat_history_system,
    message_handle_send_chat,
    // Phase 5: 网络同步系统
    setup_network_system,
    send_player_position_system,
    send_player_stats_system,
    send_chat_to_server_system,
    send_interaction_to_server_system,
    receive_player_sync_system,
    receive_npc_sync_system,
    receive_map_sync_system,
    receive_server_chat_system,
    handle_connection_events_system,
    apply_player_sync_system,
    apply_npc_sync_system,
    apply_item_spawn_system,
    sync_local_state_system,
    // Phase 6: 完整事件循环
    setup_game_loop_system,
    game_loop_system,
    process_frame_events_system,
    update_frame_stats_system,
    check_win_lose_conditions_system,
    integrate_all_systems_system,
    validate_game_state_system,
    handle_game_errors_system,
    debug_system_health_system,
    optimize_network_updates_system,
    optimize_render_system,
    profile_system_performance_system,
    message_handle_game_loop,
    message_handle_frame_stats_request,
    message_handle_system_health_request,
    message_handle_performance_report,
    // GameScene Components
    GameSceneState,
    Player,
    PlayerMovement,
    GameSceneRoot,
    HudRoot,
    PlayerInfoHud,
    ChatPanel,
    ChatInput,
    ChatMessageList,
    SkillBar,
    QuickSlotButton,
    MiniMap,
    // Phase 2: 地图系统
    MapData,
    MapTile,
    MapObject,
    // Phase 3: 对话系统
    DialogueOption,
    DialogueNode,
    DialogueTree,
    DialogueState,
    InteractionState,
    // Phase 4: 聊天系统
    ChatFilterConfig,
    ChatCommand,
    ChatCommandManager,
    ChatDisplaySettings,
    // Phase 5: 网络同步系统
    NetworkState,
    ConnectionState,
    RemotePlayer,
    PlayerSyncMessage,
    PlayerStatsSyncMessage,
    RemotePlayerSyncMessage,
    NPCSyncMessage,
    MapObjectSyncMessage,
    ChatSyncMessage,
    ItemSpawnMessage,
    ItemDespawnMessage,
    ConnectionEvent,
    NetworkErrorMessage,
    ServerTimeSyncMessage,
    // Phase 6: 完整事件循环
    GameLoopState,
    FrameStats,
    GameTimer,
    EventQueue,
    SystemHealthCheck,
    GameLoopMessage,
    RequestFrameStatsMessage,
    RequestSystemHealthMessage,
    PerformanceReportMessage,
    // GameScene Messages
    PlayerMoveMessage,
    PlayerStopMessage,
    OpenChatMessage,
    CloseChatMessage,
    SendChatMessage,
    OpenInventoryMessage,
    CloseInventoryMessage,
    OpenSkillsMessage,
    CloseSkillsMessage,
    OpenCharacterMessage,
    CloseCharacterMessage,
    ExitGameMessage,
    InteractWithNpcMessage,
    UseSkillMessage,
    PauseGameMessage,
    // Phase 3: 对话消息
    StartDialogueMessage,
    SelectDialogueOptionMessage,
    CloseDialogueMessage,
    PerformInteractionMessage,
};

